/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiAssistants: typeof import('./components/ApiAssistants.vue')['default']
    ApiFileObjects: typeof import('./components/ApiFileObjects.vue')['default']
    ApiFunction: typeof import('./components/ApiFunction.vue')['default']
    ApiThreadMessages: typeof import('./components/ApiThreadMessages.vue')['default']
    ApiThreads: typeof import('./components/ApiThreads.vue')['default']
    ApiUser: typeof import('./components/ApiUser.vue')['default']
    AppMain: typeof import('./components/AppMain.vue')['default']
    AppMessage: typeof import('./components/AppMessage.vue')['default']
    AppMicrophone: typeof import('./components/AppMicrophone.vue')['default']
    AppRun: typeof import('./components/AppRun.vue')['default']
    AppTextBlock: typeof import('./components/AppTextBlock.vue')['default']
    BtnGradient: typeof import('./components/BtnGradient.vue')['default']
    ContainerLeft: typeof import('./components/ContainerLeft.vue')['default']
    ContainerMain: typeof import('./components/ContainerMain.vue')['default']
    ContainerRight: typeof import('./components/ContainerRight.vue')['default']
    FunctionCatalogue: typeof import('./components/FunctionCatalogue.vue')['default']
    InputFile: typeof import('./components/InputFile.vue')['default']
    InputFormField: typeof import('./components/InputFormField.vue')['default']
    InputText: typeof import('./components/InputText.vue')['default']
    InputTextAreaField: typeof import('./components/InputTextAreaField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
