name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Vue.js Dependencies
      run: |
        cd app
        npm install

    - name: Build Vue.js App
      run: |
        cd app
        npm run build

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install FastAPI Dependencies
      run: |
        pip install -r requirements.txt

    # Add steps for testing, building Docker images, pushing to registry, 
    # and deploying to AWS EKS...
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::008356605572:role/oidc-role # Asegúrate de reemplazar con tus valores
        role-session-name: GitHubActions
        web-identity-token-file: ${{ steps.oidc-auth.outputs.token-path }}

    - name: Set up Kubernetes context
      run: |
        aws eks update-kubeconfig --name k8s
        kubectl config use-context arn:aws:eks:us-east-1:008356605572:cluster/k8s
        aws eks get-token --cluster-name k8s | jq -r '.status.token' > /tmp/token 
        kubectl config set-credentials oidc --token="$(cat /tmp/token)"
        kubectl config set-context arn:aws:eks:us-east-1:008356605572:cluster/k8s --user=oidc
        
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml # Asegúrate de reemplazar con tus valores